<<<<<<< HEAD
g# provisioning.yml
# 負責在 VMware 上創建所有 VM
=======
>>>>>>> cc838dccf5bb464333ddfa8f469742c40592e132
- name: 1. Provision CDN Infrastructure on VMware
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    vm_template: "My_Base_Ubuntu_Template"
    vm_datacenter: "DC02"
    vm_network: "VM Network"
    vcenter_host: "192.168.32.110"
    vcenter_user: "stephen_yang@ysflco.com"
    vcenter_pass: "P25Uz9-P25Uz9"
    target_esxi_host: "192.168.34.242"
    target_ssh_user: "ansible"
    target_ssh_pass: "test1234"

  tasks:
    - name: Create required VMs
      community.vmware.vmware_guest:
        name: "{{ item.name }}"
        hostname: "{{ vcenter_host }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no
        template: "{{ vm_template }}"
        datacenter: "{{ vm_datacenter }}"
        esxi_hostname: "{{ target_esxi_host }}"
        folder: "/"
        networks:
          - name: "{{ vm_network }}"
        hardware:
          memory_mb: "{{ item.mem }}"
          num_cpus: "{{ item.cpu }}"
      register: new_vms
      loop:
        - { name: 'cdn-node-01', group: 'cdn_nodes', mem: 4096, cpu: 2 }

    - name: Wait 120 seconds for networking
      pause:
        seconds: 120

    - name: Wait for SSH ready
      wait_for_connection:
        delay: 10
        timeout: 300
      loop: "{{ new_vms.results }}"
      loop_control:
        loop_var: vm
      vars:
        ansible_host: "{{ vm.instance.ipv4_address }}"
        ansible_user: "{{ target_ssh_user }}"
        ansible_password: "{{ target_ssh_pass }}"
      when: vm.instance.ipv4_address is defined

    - name: Add new VMs to inventory
      add_host:
        hostname: "{{ vm.instance.ipv4_address }}"
        groupname: "{{ vm.item.group }}"
        ansible_user: "{{ target_ssh_user }}"
        ansible_password: "{{ target_ssh_pass }}"
      loop: "{{ new_vms.results }}"
      loop_control:
        loop_var: vm
      when: vm.instance.ipv4_address is defined