# provisioning.yml
# 負責在 VMware 上創建所有 VM
- name: 1. Provision CDN Infrastructure on VMware
  hosts: localhost 
  connection: local
  gather_facts: no
  
  # 這些變數由 AWX 憑證自動注入
  vars:
    # ⭐️ 替換為您的 Linux 範本名稱 ⭐️
    vm_template: "My_Base_Ubuntu_Template" 
    # ⭐️ 替換為您的資料中心名稱 ⭐️
    vm_datacenter: "DC02"  
    # ⭐️ 替換為您的叢集名稱 ⭐️
    #vm_cluster: "My_Cluster"        
    # ⭐️ 替換為您的網路名稱 ⭐️
    vm_network: "VM Network"
    vcenter_host: "192.168.32.110"   # 填寫您的 vCenter IP
    vcenter_user: "stephen_yang@ysflco.com"
    vcenter_pass: "P25Uz9-P25Uz9"
    # ⭐️ 必須新增此變數並填寫 ESXi 主機名稱 ⭐️
    target_esxi_host: "192.168.34.242"
    target_ssh_user: "ansible" # ⭐️ 替換為新 VM 的實際登錄用戶名 ⭐️
    target_ssh_pass: "test1234" # ⭐️ 替換為新 VM 的實際密碼 ⭐️        
    
  tasks:
    - name: Create required VMs on specified ESXi host
      community.vmware.vmware_guest:
        name: "{{ item.name }}"
        # vCenter 連線資訊
        hostname: "{{ vcenter_host }}" 
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no

        template: "{{ vm_template }}" # 必須指定從哪個範本克隆
        
        # ⭐️ 僅使用 Datacenter 和 ESXi 主機來定位 ⭐️
        datacenter: "{{ vm_datacenter }}" 
        esxi_hostname: "{{ target_esxi_host }}" # 這是您要強制部署的主機
        #cluster: "{{ vm_cluster }}"
        folder: "/"
        networks:
          - name: "{{ vm_network }}"
            # 確保您的範本設定使用 DHCP 或這裡設定的 IP
        hardware:
          memory_mb: "{{ item.mem }}"
          num_cpus: "{{ item.cpu }}"
        
      register: new_vms
      loop:
        # 創建 VM 列表
        - { name: 'cdn-node-01', group: 'cdn_nodes', mem: 4096, cpu: 2 }
        - { name: 'api-backend-01', group: 'api_backends', mem: 2048, cpu: 1 }
        - { name: 'user-frontend-01', group: 'user_frontends', mem: 2048, cpu: 1 }

    - name: Wait 120 seconds for VM networking to come up
      ansible.builtin.pause:
        seconds: 120
      
    - name: Wait for new VMs to be reachable via SSH
      ansible.builtin.wait_for_connection:
        delay: 5 # 每 5 秒檢查一次
        timeout: 300 # 最長等待 5 分鐘
      # 假設您的 VM 範本設定了 DHCP，Ansible 會嘗試連線到 VM 的 IP
      delegate_to: "{{ item.instance.ipv4_address }}" 
      loop: "{{ new_vms.results | json_query('[].instance') }}" 
      when: item.instance.ipv4_address is defined

    - name: Dynamically add new VMs to AWX Inventory
      ansible.builtin.add_host:
        hostname: "{{ item.instance.ipv4_address }}"
        groupname: "{{ item.item.group }}" 
        
        # ⭐️ 修正為引用定義的變數 ⭐️
        ansible_user: "{{ target_ssh_user }}"
        ansible_password: "{{ target_ssh_pass }}"
        
      delegate_to: localhost
      loop: "{{ new_vms.results | json_query('[].instance') }}" 
      when: item.instance.ipv4_address is defined